Bad actor with IP violation and rug pull
oceanprotocol/list-purgatory pull request #25
Opened 2020-11-29 13:38 UTC by kaimeinke

This actor 0x2D3fb3096F020029A49A45c88253A4CD0BC2503F pulled data from Kaggle (URI: https://www.kaggle.com/gsutters/the-human-freedom-index?select=hfi_cc_2018.csv) without giving the proper license information on did:op:3CeA3612EA153a6b8Ce269E6a93E797EE73214F1 and performed a rug pull.

2020-11-29 16:39 UTC, kaimeinke commented
Meanwhile the owner of the pool has confirmed the rugpull was intentional and the community has discussed the issue with the content provider after investigation by Agent_K.

This has revealed that other addresses were used to create others sets that were rugpulled by the same actor. 

Other addresses will need to be added with another pull request later.

![Screenshot_20201129-155944_Telegram](https://user-images.githubusercontent.com/59994024/100547928-ca2f8980-3269-11eb-9f99-369b95bf7a03.jpg)

2020-11-29 16:55 UTC, kaimeinke commented
The new address 0x359a76dB7aFDAd46f0e2C6699eC768c1064C86Ca has been added with a new commit. This is the creator adress for did:op:6Ee6f092229E32c708569f98Ad0E6A7206371E94

This is the transaction that links both accounts. https://etherscan.io/tx/0x637ccbb860a1ebfe0131d224280ca0c9972a46d3241490748c78d16399e2bb77

2020-12-02 07:20 UTC, kaimeinke commented
Will this request go any further or did I do something wrong that blocks a merge? 

Asset https://market.oceanprotocol.com/asset/did:op:3CeA3612EA153a6b8Ce269E6a93E797EE73214F1 is still live.
Asset https://market.oceanprotocol.com/asset/did:op:6Ee6f092229E32c708569f98Ad0E6A7206371E94 is still live.

Both belong in purgatory.

2020-12-02 09:25 UTC, kremalicious commented on list-accounts.json
>      }
needs a comma here

```suggestion
    },
```

2020-12-02 09:26 UTC, kremalicious commented on list-accounts.json
> +    }
and here too

```suggestion
    },
```

2020-12-02 09:29 UTC, kremalicious commented
process note: putting an account into purgatory will not automatically put its assets into purgatory. If this is desired, `list-assets.json` would need to be edited as part of this PR too.

2020-12-02 11:02 UTC, kaimeinke commented
Thanks a lot for the help @kremalicious , I should have seen this and now I will look out for it. I will add the assets to `list-assets.json` as well.

2020-12-08 10:57 UTC, daneklustig requested changes
Please use one of the categories for putting datasets into purgatory: rug pull / sensitive data / impersonation / ip infringement / violation

2020-12-09 10:26 UTC, daneklustig approved these changes

2020-12-09 10:26 UTC, merged